name: android_window
description: A flutter plugin used to create android floating window
version: 0.0.0
homepage: https://github.com/qiuxiang/flutter-android-window

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pigeon: ^1.0.7

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.android_window
        pluginClass: AndroidWindowPlugin
