name: release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: bruceadams/get-release@v1.2.3
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build
        run: |
          export version=$(echo ${{ steps.release.outputs.tag_name }} | sed s/v//)
          sed -i -r "s/version: .*/version: $version/" pubspec.yaml
          sed -i "1s/^/## $version\n\n${{ steps.release.outputs.body }}\n\n/" CHANGELOG.md
          mkdir android/src/main/java/qiuxiang/android_window -p
          flutter pub get
          flutter pub run pigeon --input lib/pigeon.dart --dart_out lib/pigeon.g.dart --java_out android/src/main/java/qiuxiang/android_window/Pigeon.java --java_package "qiuxiang.android_window"
          cd example
          flutter build apk --target-platform android-arm64
      - name: Publish
        run: |
          echo '${{ secrets.CREDENTIALS_JSON }}' > $(which flutter | sed -r 's/bin\/flutter/.pub-cache\/credentials.json/')
          flutter pub publish -f
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./example/build/app/outputs/flutter-apk/app-release.apk
          asset_name: example.apk
          asset_content_type: application/vnd.android.package-archive
